name: Automatic Documentation for Launcher

on:
  pull_request:

jobs:
  update_docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Launcher
      id: install-launcher
      env:
        REF: ${{ github.head_ref }}
        REPO: ${{ github.repository }}
      run: cargo install --git "https://github.com/$REPO" --branch "$REF" text-generation-launcher

    - name: Check launcher Docs are up-to-date
      run: |
        echo text-generation-launcher --help
        python update_doc.py --check
